// generated by cdktf get
export * from './dynamodb-contributor-insights';
export * from './dynamodb-global-table';
export * from './dynamodb-kinesis-streaming-destination';
export * from './dynamodb-table';
export * from './dynamodb-table-item';
export * from './dynamodb-table-replica';
export * from './dynamodb-tag';
export * from './data-aws-dynamodb-table';

