// generated by cdktf get
export * from './service-discovery-http-namespace';
export * from './service-discovery-instance';
export * from './service-discovery-private-dns-namespace';
export * from './service-discovery-public-dns-namespace';
export * from './service-discovery-service';
export * from './data-aws-service-discovery-dns-namespace';

