// generated by cdktf get
export * from './efs-access-point';
export * from './efs-backup-policy';
export * from './efs-file-system';
export * from './efs-file-system-policy';
export * from './efs-mount-target';
export * from './data-aws-efs-access-point';
export * from './data-aws-efs-access-points';
export * from './data-aws-efs-file-system';
export * from './data-aws-efs-mount-target';

